### ISSUE TITLE
Error: Select task failed calling Plugins::ShairTunes2W::Plugin::handleSocketRead

### ISSUE THREAD

**Issue by ebin-dev** [philippe44/ShairTunes2#59]
I have tested the current Version of LMS 9.1.0 with ShairTunes2W 1.7.2 on Debian Trixie (arm64, linux 6.12.41). Unfortunately ShairTunes2W is not loaded by LMS - the following error is thrown:

**Select task failed calling Plugins::ShairTunes2W::Plugin::handleSocketRead: PKCS#1 1.5 is disabled as it is known to be vulnerable to marvin attacks**

It is reported [here](https://forums.lyrion.org/forum/user-forums/3rd-party-software/96885-announce-shairtunes-plugin/page26?view=thread#post1776225) that the compatible libssl version for ShairTunes2W 1.7.2 is libssl.so.1.0. However Debian Trixie ships with libssl 3.5 which is incompatible. Would it be possible to adapt the dependencies such that ShairTunes2W runs out of the box on Trixie/LMS9.1.0 ?

Side Note: ShairTunes2W / LMS 9.0.3 works without any issues on Debian Bookworm (arm64, linux 6.12.41).

**Log file:**
[25-08-11 14:08:04.0579] main::init (282) Starting Lyrion Music Server (v9.1.0, 1752577284, Wed Jul 16 03:17:09 UTC 2025) perl 5.040001 - aarch64-linux-gnu-thread-multi
[25-08-11 14:08:04.4000] main::init (555) Server done init: http://192.168.240.30:9000/
[25-08-11 14:08:06.3580] Plugins::ShairTunes2W::Plugin:PlayerSubscriptionCh ange (319) request=client new client=Slim::Player::Receiver=ARRAY(0xaaaaeaae0fd0 ) 00:04:20:17:ae:95
[25-08-11 14:08:06.3584] Plugins::ShairTunes2W::Plugin::createListenPort (399) Created listener on port 33615
[25-08-11 14:08:06.3586] Plugins::ShairTunes2W::Plugin:PublishPlayer (435) start avahi-publish-service "SB-xxx"
[25-08-11 14:08:06.3627] Plugins::ShairTunes2W::Plugin::addPlayer (346) create client Slim::Player::Receiver=ARRAY(0xaaaaeaae0fd0) with proc Proc::Background=HASH(0xaaaaeaae0ce8)
[25-08-11 14:08:06.4373] Plugins::ShairTunes2W::Plugin:PlayerSubscriptionCh ange (319) request=client new client=Slim::Player::Boom=ARRAY(0xaaaaeac1ee98) 00:04:20:1f:91:31
[25-08-11 14:08:06.4377] Plugins::ShairTunes2W::Plugin::createListenPort (399) Created listener on port 42067
[25-08-11 14:08:06.4379] Plugins::ShairTunes2W::Plugin:PublishPlayer (435) start avahi-publish-service "SB-yyy"
[25-08-11 14:08:06.4415] Plugins::ShairTunes2W::Plugin::addPlayer (346) create client Slim::Player::Boom=ARRAY(0xaaaaeac1ee98) with proc Proc::Background=HASH(0xaaaaeb6f8388)
[25-08-11 14:08:52.9353] Plugins::ShairTunes2W::Plugin::handleSocketConnect (478) New connection from: 192.168.240.44
[25-08-11 14:08:52.9358] Plugins::ShairTunes2W::Plugin::createListenPort (399) Created listener on port 42295
[25-08-11 14:08:52.9388] Slim::Networking::IO::Select::__ANON__ (131) **Error**: Select task failed calling Plugins::ShairTunes2W::Plugin::handleSocketRead: PKCS#1 1.5 is disabled as it is known to be vulnerable to marvin attacks. at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/ShairTunes2W/Plugin.pm line 728.
; fh=IO::Socket::INET=GLOB(0xaaaaebb162a0)
[25-08-11 14:08:58.0731] Plugins::ShairTunes2W::Plugin::handleSocketRead (593) Closed: IO::Socket::INET=GLOB(0xaaaaebb162a0)
[25-08-11 14:08:59.8844] Plugins::ShairTunes2W::Plugin::handleSocketConnect (478) New connection from: 192.168.240.44
[25-08-11 14:08:59.8848] Plugins::ShairTunes2W::Plugin::createListenPort (399) Created listener on port 40233
[25-08-11 14:08:59.8859] Slim::Networking::IO::Select::__ANON__ (131) **Error**: Select task failed calling Plugins::ShairTunes2W::Plugin::handleSocketRead: PKCS#1 1.5 is disabled as it is known to be vulnerable to marvin attacks. at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/ShairTunes2W/Plugin.pm line 728.
; fh=IO::Socket::INET=GLOB(0xaaaae8768ad0)
[25-08-11 14:09:29.8972] Plugins::ShairTunes2W::Plugin::handleSocketRead (593) Closed: IO::Socket::INET=GLOB(0xaaaae8768ad0)

**Comment by cotchon** [comment]
Same behaviour here, trixie, Lyrion 9.1.0

**Comment by Tecko71** [comment]
yes I installed 9.0.3 same problem. Trixie related I think

**Comment by cotchon** [comment]
chat gpt said : 

PKCS#1 v1.5 padding (used by $rsa->use_pkcs1_padding) is considered vulnerable to the Marvin attack (and several older oracle-style attacks such as Bleichenbacher’s). The correct mitigation is to switch to OAEP padding (Optimal Asymmetric Encryption Padding), which is part of PKCS#1 v2.x and is secure against those vulnerabilities

Apparently this is not implemented in Crypt::OpenSSL::RSA so he suggest either to recompile the package to include OAEP feature
OR use of Crypt::PK::RSA (CryptX module)

If this can help ...

**Comment by philippe44** [comment]
> When running 1.9.1, server log is:
> 
> ```
> [25-10-15 06:41:19.3409] main::init (282) Starting Lyrion Music Server (v9.1.0, 1760170925, Sat Oct 11 12:02:02 UTC 2025) perl 5.040001 - x86_64-linux-gnu-thread-multi
> [25-10-15 06:41:21.6122] Slim::Utils::PluginManager::load (396) Warning: Couldn't call Plugins::ShairTunes2W::Plugin->initPlugin: Attempt to reload Crypt/PK/RSA.pm aborted.
> Compilation failed in require at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/ShairTunes2W/Plugin.pm line 222.
> [25-10-15 06:41:21.8593] main::init (555) Server done init: http://192.168.100.101:9000
> [25-10-15 06:41:51.1477] Plugins::ShairTunes2W::Utils::checkHelper (121) executable not having 'x' permission, correcting
> [25-10-15 06:41:51.1479] Plugins::ShairTunes2W::Plugin::stop_mDNS (303) Killing all processes
> [25-10-15 06:42:06.2834] main::init (282) Starting Lyrion Music Server (v9.1.0, 1760170925, Sat Oct 11 12:02:02 UTC 2025) perl 5.040001 - x86_64-linux-gnu-thread-multi
> [25-10-15 06:42:07.1072] Slim::Utils::PluginManager::load (396) Warning: Couldn't call Plugins::ShairTunes2W::Plugin->initPlugin: Attempt to reload Crypt/PK/RSA.pm aborted.
> Compilation failed in require at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/ShairTunes2W/Plugin.pm line 222.
> ```
>
Also, please set plugin's loglevel in LMS settings at info so I can have better traces.

**Comment by mic-hall** [comment]
> I added it here because [@dierochade](https://github.com/dierochade) had the same message, not trying ti hijack your issue, but it appears to be the same. I also opened a bash prompt in the running docker container and installed libcryptx-perl, but that did not seem to help.

Did you disable the package in the plugin? (/config/cache/InstalledPlugins/Plugins/ShairTunes2W/elib/5.36)

**Comment by Elissen** [comment]
Updated to 1.9.13 and it works, thank you!

**Comment by ebin-dev** [comment]
LMS 9.0.4 / ShairTunes2W 1.9.13 now works on Debian Trixie (arm64, linux 6.12.55), thank you !
